language: cpp
os: linux
dist: focal
notifications:
  email: false

jobs:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lcov
            - g++-7
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-7; sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90"

    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - lcov
          update: true

      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++"


before_install:
  - eval "${MATRIX_EVAL}"

install:
  - cmake -Sexec -Bbuild -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_CXX_COMPILER=$CXX_COMPILER
  - cd build
  - make

script:
  - make coverage

after_success:
  - lcov --list coverage_out.info.cleaned  # Show test report in travis log.
  # Install coverals gem for uploading coverage to coveralls.
  - gem install coveralls-lcov
  - coveralls-lcov coverage_out.info.cleaned  # uploads to coveralls
  - bash <(curl -s https://codecov.io/bash) -f coverage_out.info.cleaned || echo "Codecov did not collect coverage reports"
