version: '{build}-{branch}'

#clone_folder:
#    C:/projects/{APPVEYOR_PROJECT_NAME}

branches:
    only:
        - master

image: Visual Studio 2019

configuration:
    - Debug
    - Release

platform: x64

matrix:
    fast_finish: false

environment:
    CMAKE_GENERATOR: Visual Studio 16 2019
    BUILD_FOLDER: build

before_build:
#    - mkdir %BUILD_FOLDER%
#    - cd %BUILD_FOLDER%
#    - cmake -G "%CMAKE_GENERATOR%" ..
    - cmake -G "%CMAKE_GENERATOR%"

build:
#    project: {APPVEYOR_BUILD_FOLDER}/{BUILD_FOLDER}/{APPVEYOR_PROJECT_NAME}.sln # cannot use %BUILD_FOLDER%/galToolbox.sln
    project: galToolbox.sln
    parallel: true
    verbosity: minimal
