version: '{build}-{branch}'

branches:
    only:
        - master

image: Visual Studio 2019

configuration:
    - Debug
    - Release

platform: x64

matrix:
    fast_finish: false

environment:
    CMAKE_GENERATOR: Visual Studio 16 2019
    BUILD_FOLDER: build

before_build:
    - mkdir %BUILD_FOLDER%
    - cd %BUILD_FOLDER%
    - cmake -G "%CMAKE_GENERATOR%" ..

build:
    project: ./build/galToolbox.sln # cannot use %BUILD_FOLDER%/galToolbox.sln
    parallel: true
    verbosity: minimal
