name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        configuration:
          - Debug

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang

# todo: why just msvc error?
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(12): message : see reference to function template instantiation 'auto `anonymous-namespace'::square_nums<0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100>(size_t,std::integer_sequence<size_t,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100>)' being compiled [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(47): message : see reference to function template instantiation 'auto `anonymous-namespace'::const_nums<101>(size_t)' being compiled [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(5,2): error C2780: 'std::array<_Ty,_Size> std::array(void)': expects 0 arguments - 101 provided [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\tuple(886): message : see declaration of 'std::array' [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(5,2): error C2780: 'std::array<_Ty,_Size> std::array(std::array<_Ty,_Size>)': expects 1 arguments - 101 provided [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\tuple(886): message : see declaration of 'std::array' [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(6,18): error C2737: 'nums': 'constexpr' object must be initialized [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(5,2): error C3536: 'nums': cannot be used before it is initialized [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(5,2): error C2109: subscript requires array or pointer type [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(47,38): error C2120: 'void' illegal with all types [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(54,22): error C2079: 'array' uses undefined class 'std::array<int,4>' [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(54,41): error C2440: 'initializing': cannot convert from 'initializer list' to 'int' [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(54,30): message : The initializer contains too many elements [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(56,16): error C2672: '`anonymous-namespace'::a2t': no matching overloaded function found [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(56,25): error C2784: 'auto `anonymous-namespace'::a2t(const std::array<_Ty,_Size> &)': could not deduce template argument for 'const std::array<_Ty,_Size> &' from 'int' [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(28): message : see declaration of '`anonymous-namespace'::a2t' [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(57,44): error C3536: 'tuple': cannot be used before it is initialized [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(57,45): error C3539: a template-argument cannot be a type that contains 'auto' [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#D:\a\galStarterTemplate\galStarterTemplate\test\test\test.cpp(58,45): error C2607: static assertion failed [D:\a\galStarterTemplate\galStarterTemplate\build\StarterTemplateTest.vcxproj]
#          - toolchain: windows-msvc
#            os: windows-latest
#            compiler: msvc

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure (${{ matrix.configuration }})
        run: cmake -Stest -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: Build with ${{ matrix.compiler }}
        run: cmake --build build

      - name: Test
        working-directory: build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest -C ${{ matrix.configuration }}
