name: windows

on:
    push:
    pull_request:

jobs:
    build-and-test:
        
        name: ${{ matrix.toolchain }}
        runs-on: ${{ matrix.os }}
        
        strategy:
            matrix:
                toolchain:
                    - windows-msvc
                
                configuration:
                    - Release
                
                include:
                    -   toolchain: windows-msvc
                        os: windows-latest
                        compiler: msvc
        
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v2
                with:
                    submodules: true
            
            -   name: Install boost
                uses: MarkusJx/install-boost@v1.0.1
                id: install-boost
                with:
                    # REQUIRED: Specify the required boost version
                    # A list of supported versions can be found here:
                    # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
                    boost_version: 1.73.0
            
            -   name: Configure (${{ matrix.configuration }})
                run: cmake -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
                env:
                    BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
            
            -   name: Build with ${{ matrix.compiler }}
                run: cmake --build build

#      - name: Test
#        working-directory: build
#        env:
#          CTEST_OUTPUT_ON_FAILURE: 1
#        run: ctest -C ${{ matrix.configuration }}
